variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

strategy:
  matrix:
    mac:
      imageName: "macOS-latest"
      nodeVersion: "14.x"
      buildPlatform: "mac"
    windows:
      imageName: "windows-latest"
      nodeVersion: "14.x"
      buildPlatform: "win"

pool:
  vmImage: $(imageName)

steps:
  # Set node version
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)
  # Cache yarn deps
  - task: Cache@2
    inputs:
      key: 'yarn | "$(Agent.OS)" | yarn.lock'
      restoreKeys: |
        yarn | "$(Agent.OS)"
        yarn
      path: $(YARN_CACHE_FOLDER)
    displayName: Cache Yarn packages
  # Install deps with yarn
  - script: yarn --frozen-lockfile
